// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using AppKit;
using Triviador.ViewModels;

namespace Triviador.Views
{
	public partial class LobbyView : NSViewController
	{
        public LobbyViewModel ViewModel { get; set; }

		public LobbyView (IntPtr handle) : base (handle)
		{
            ViewModel = new LobbyViewModel();
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            LobbyTF.Editable = false;
            LobbyTF.StringValue = ViewModel.CurrentPlayer.Nickname;
        }

        partial void BackButtonPressed(AppKit.NSButton sender)
		{
            var storyboard = NSStoryboard.FromName("Main", null);
            var previousVC = storyboard.InstantiateControllerWithIdentifier("RegisterView") as RegisterView;
            View.Window.ContentViewController = previousVC;
        }

        partial void StartGameButtonPressed(AppKit.NSButton sender)
        {
            var storyboard = NSStoryboard.FromName("Main", null);
            var nextVC = storyboard.InstantiateControllerWithIdentifier("MapView") as MapView;
            View.Window.ContentViewController = nextVC;
        }
    }
}
