// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Triviador
{
	public partial class MapView : NSViewController
	{
		public MapView (IntPtr handle) : base (handle)
		{
		}
	}
}
