// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using AppKit;
using Triviador.ViewModels;

namespace Triviador.Views
{
	public partial class RegisterView : NSViewController
	{
        public RegisterViewModel ViewModel { get; set; }

        public RegisterView(IntPtr handle) : base(handle)
        {
            ViewModel = new RegisterViewModel();
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            // Do any additional setup after loading the view.
        }

        partial void ApplyButtonPressed(AppKit.NSButton sender)
        {
            if (NickNameTF.StringValue != "")
            {
                ViewModel.CurrentPlayer.Nickname = NickNameTF.StringValue;
                var storyboard = NSStoryboard.FromName("Main", null);
                var lobbyVC = storyboard.InstantiateControllerWithIdentifier("LobbyView") as LobbyView;
                lobbyVC?.ViewModel.UpdatePlayer(ViewModel.CurrentPlayer);
                View.Window.ContentViewController = lobbyVC;
            } else {
                NSAlert alert = new NSAlert();
                alert.MessageText = "Please eneter a valid player name!";
                alert.AddButton("Apply");
                alert.RunModal();
            }
        }

        public override NSObject RepresentedObject
        {
            get
            {
                return base.RepresentedObject;
            }
            set
            {
                base.RepresentedObject = value;
                // Update the view, if already loaded.
            }
        }
    }
}
