// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using AppKit;
using Triviador.ViewModels;

namespace Triviador.Views
{
	public partial class RegisterView : NSViewController
	{
        public PlayerViewModel ViewModel { get; set; }

        public RegisterView(IntPtr handle) : base(handle)
        {
            ViewModel = new PlayerViewModel();
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            // Do any additional setup after loading the view.
        }

        partial void ApplyButtonPressed(AppKit.NSButton sender)
        {
            ViewModel.CurrentPlayer.Nickname = NickNameTF.StringValue;

            var storyboard = NSStoryboard.FromName("Main", null);
            var lobbyVC = storyboard.InstantiateControllerWithIdentifier("LobbyView") as LobbyView;
            lobbyVC?.ViewModel.UpdatePlayer(ViewModel.CurrentPlayer);
            View.Window.ContentViewController = lobbyVC;
        }

        public override NSObject RepresentedObject
        {
            get
            {
                return base.RepresentedObject;
            }
            set
            {
                base.RepresentedObject = value;
                // Update the view, if already loaded.
            }
        }
    }
}
